export const API_KEY = "03f30ab004089f24c28d0fcdf3e9e584"
export const FETCH_WHEATHER_REQUEST = 'FETCH_WHEATHER_REQUEST'
export const FETCH_WHEATHER_SUCCESS = 'FETCH_WHEATHER_SUCCESS'
export const FETCH_WHEATHER_FAILURE = 'FETCH_WHEATHER_FAILURE'
export const FETCH_HISTORY='FETCH_HISTORY'